language: cpp

os:
  - osx

compiler:
  - clang

script:
  - brew install sfml
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - cd ..
  - ctest

notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify?secret=KekLolCheburek
  email:
    - nagov-mark@mail.ru