language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

install:
  - ./travis_ci/install-$TRAVIS_OS_NAME.sh

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build

notifications:
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify?secret=KekLolCheburek
  email:
    - nagov-mark@mail.ru